package com.appzone.sciencealerts.hibernate.entity;
// Generated Oct 29, 2012 11:05:03 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppComments generated by hbm2java
 */
@Entity
@Table(name="appcomments"
    ,catalog="ScienceAlerts"
)
public class AppComments  implements java.io.Serializable {


     private Long id;
     private SmsSender smssender;
     private String comment;
     private String isChecked;

    public AppComments() {
    }

	
    public AppComments(String isChecked) {
        this.isChecked = isChecked;
    }
    public AppComments(SmsSender smssender, String comment, String isChecked) {
       this.smssender = smssender;
       this.comment = comment;
       this.isChecked = isChecked;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SenderId")
    public SmsSender getSmssender() {
        return this.smssender;
    }
    
    public void setSmssender(SmsSender smssender) {
        this.smssender = smssender;
    }
    
    @Column(name="COMMENT", length=500)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    
    @Column(name="IsChecked", nullable=false, length=1)
    public String getIsChecked() {
        return this.isChecked;
    }
    
    public void setIsChecked(String isChecked) {
        this.isChecked = isChecked;
    }




}


