package com.appzone.sciencealerts.hibernate.entity;
// Generated Oct 29, 2012 11:05:03 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Help generated by hbm2java
 */
@Entity
@Table(name="help"
    ,catalog="ScienceAlerts"
)
public class Help  implements java.io.Serializable {


     private Integer id;
     private String helpText;

    public Help() {
    }

    public Help(String helpText) {
       this.helpText = helpText;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="HelpText", length=160)
    public String getHelpText() {
        return this.helpText;
    }
    
    public void setHelpText(String helpText) {
        this.helpText = helpText;
    }




}


