package com.appzone.sciencealerts.hibernate.entity;
// Generated Oct 29, 2012 11:05:03 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsSender generated by hbm2java
 */
@Entity
@Table(name="smssender"
    ,catalog="ScienceAlerts"
)
public class SmsSender  implements java.io.Serializable {


     private Long id;
     private String address;
     private String userName;
     private String isReg;
     private Long marks;
     private String isSchedularActive;
     private Date joinedDate;
     private Date lastActiveTime;
     private String isActive;
     private Set<AppComments> appcommentses = new HashSet<AppComments>(0);
     private Set<AppComments> appcommentses_1 = new HashSet<AppComments>(0);

    public SmsSender() {
    }

	
    public SmsSender(String address, String isReg, String isSchedularActive, String isActive) {
        this.address = address;
        this.isReg = isReg;
        this.isSchedularActive = isSchedularActive;
        this.isActive = isActive;
    }
    public SmsSender(String address, String userName, String isReg, Long marks, String isSchedularActive, Date joinedDate, Date lastActiveTime, String isActive, Set<AppComments> appcommentses, Set<AppComments> appcommentses_1) {
       this.address = address;
       this.userName = userName;
       this.isReg = isReg;
       this.marks = marks;
       this.isSchedularActive = isSchedularActive;
       this.joinedDate = joinedDate;
       this.lastActiveTime = lastActiveTime;
       this.isActive = isActive;
       this.appcommentses = appcommentses;
       this.appcommentses_1 = appcommentses_1;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="Address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Column(name="UserName", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="IsReg", nullable=false, length=1)
    public String getIsReg() {
        return this.isReg;
    }
    
    public void setIsReg(String isReg) {
        this.isReg = isReg;
    }
    
    @Column(name="Marks")
    public Long getMarks() {
        return this.marks;
    }
    
    public void setMarks(Long marks) {
        this.marks = marks;
    }
    
    @Column(name="IsSchedularActive", nullable=false, length=1)
    public String getIsSchedularActive() {
        return this.isSchedularActive;
    }
    
    public void setIsSchedularActive(String isSchedularActive) {
        this.isSchedularActive = isSchedularActive;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="JoinedDate", length=19)
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastActiveTime", length=19)
    public Date getLastActiveTime() {
        return this.lastActiveTime;
    }
    
    public void setLastActiveTime(Date lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }
    
    @Column(name="IsActive", nullable=false, length=1)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="smssender")
    public Set<AppComments> getAppcommentses() {
        return this.appcommentses;
    }
    
    public void setAppcommentses(Set<AppComments> appcommentses) {
        this.appcommentses = appcommentses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="smssender")
    public Set<AppComments> getAppcommentses_1() {
        return this.appcommentses_1;
    }
    
    public void setAppcommentses_1(Set<AppComments> appcommentses_1) {
        this.appcommentses_1 = appcommentses_1;
    }

}


